### ISSUE TITLE
Problems with Windows 10 Anniversary Update

### ISSUE THREAD

**Issue by MarcusSpecht** [maximcus/WPFTabTip#2]
So far I love that you are tackling this problem. I am tinkering around with TabTip and osk since forever. So problem is after update to windows 10 anniversary some things seem to be broken.

1. dotnet 4.6.2 promised to enable focus tracking including toggling soft keyboard, but it doesn't so far. At least not for me.

1.1 [Announcing .NET Framework 4.6.2](https://blogs.msdn.microsoft.com/dotnet/2016/08/02/announcing-net-framework-4-6-2/)

1.2 [forum about not working really](https://social.msdn.microsoft.com/Forums/vstudio/en-US/540e17a1-8b60-4f67-bd55-c20fb7c07bda/wpf-net-462-windows-10-soft-keyboard-support-not-working-?forum=wpf)

Problem is executing TabTip.exe doesn't actually open the soft keyboard anymore. See [stackoverflow discussion](http://stackoverflow.com/questions/38774139/show-touch-keyboard-tabtip-exe-in-windows-10-anniversary-edition). The proposed solution with EnableDesktopModeAutoInvoke doesn't work for me.

If we are lucky this should get resolved with an update. Until than I don't know how to proceed now.

**Comment by MarcusSpecht** [comment]
I just tried out the following:

1 run your uitest
2 focus texbox (soft keyboard not coming up)
3 toggle softkeyboard using windows 10 tray button
4 click your uitest do nothing button
5 softkeyboard is hiding with animation

Could it be that the softkeyboard is always running now so executing second time doesn't launch the window? Should we use show window instead or something similar?

**Comment by MarcusSpecht** [comment]
After killing TabTip.exe (Touch Keyboard and Handwriting Panel Helper) in TaskManager it restarts instantly.

**Comment by maximcus** [comment]
I tested it on Win 10, and it worked with "EnableDesktopModeAutoInvoke". But i don't know if it was Win 10 anniversary or not... Thing is i don't have much time to spare to investigate this issue, and my users use Win 8.1. I will come back to this when i will have time. Meanwhile try to find out how to open TabTip on Win 10 anniversary programmatically.

And can you tell me, when you click on TabTip tray button it opens every time? and do you have hardware keyboard attached to your machine?

**Comment by maximcus** [comment]
Ok, i found out that one of my machines updated to anniversary, so at least i have a test machine. But in my case it is throwing an exception, so i'll have to deal with it first.

**Comment by MarcusSpecht** [comment]
It works in .net 4.6.2 and Windows 10 after anniversary update but only you have no physical keyboard present. This is done by .net automatically. Using the .net mechanism and yor solution seems to disturb the softkeyboard. 

So if running in .net 4.6.2 and after the anniversary update your WpfTabTip should do nothing but before that it should work fine as it is? 

In Desktop Mode with keyboard attached I couldn't get the soft keyboard to show.

**Comment by maximcus** [comment]
@MarcusSpecht can you please test this branch: https://github.com/maximcus/WPFTabTip/tree/registryProblem

I tested my solution on anniversary update in Desktop Mode with keyboard attached and everything is working. 
What do you mean by saying "disturb the soft keyboard"?
I will test everything again tomorrow.

**Comment by MarcusSpecht** [comment]
I just downloaded tested branch. First thing i gotta say is I am using a Surface Pro 3. It either doesn't work at all or the Soft Keyboard shows and hides instantly when focusing a textbox. Following scenarios and outcome.

Important: I have .net 4.6.2 installed manually. I am not sure if it is already deployed with Windows 10.

1. Desktop Mode + Surface Cover Detached + Physical Cover detached -> shows and hides
2. Dekstop Mode + Surface Cover Detached + Physical Cover attached -> shows and hides
3. Desktop Mode + Surface Cover Attached + Physical Cover attached -> nothing

I checked if disabling the following in TabTipAutomation doesn't hide TabTip after each show but it doesn't.

`AutomateTabTipClose(FocusSubject.AsObservable(), TabTipClosedSubject);`

What .net runtime is your application running/targeting? A comment here suggests that even if you do not target .net 4.6.2 the promised WPF mechanism kicks in if .net 4.6.2 is installed.

see [forum](https://social.msdn.microsoft.com/Forums/vstudio/en-US/540e17a1-8b60-4f67-bd55-c20fb7c07bda/wpf-net-462-windows-10-soft-keyboard-support-not-working-?forum=wpf)

I am also done for today. Talk to you tomorrow. Thx for everything so far.

**Comment by MarcusSpecht** [comment]
Hi, i created a class to detect .net framework version in case you want to check against 4.6.2.

[DotNetVersion.cs](https://gist.github.com/MarcusSpecht/6c431f3efe7c84e9c9594f26afdb7cb0)

**Comment by maximcus** [comment]
UITest project is targeting .Net 4.5, as is WPFTabTip.

I was able to test WPFTabTip on Windows 10 Anniversary in apps using .NET 4.5 and .Net 4.6.2. I was testing in both Desktop and Tablet mode with keyboard attached, and everything worked perfectly.

I cannot test without keyboard, because the only machine with Win 10 i have is a notebook. And i think that issues you describe is only present on a device without keyboard attached.

I tried to test in VirtualBox but Win 10 keeps crashing under me for some reason.

So i cannot reproduce your problem, and without that there is little i can do. My suggestion now is that development of a solution to this problems is in the hands of those who can reproduce it (after all that is one of the benefits of open source). So if you, or anybody else would create a pool request resolving this issue i would happily accept it (maybe after some refactoring and if nothing is broken).

If nobody would come up with a solution, i will resolve this issue eventually, but when i will have a chance to do that i do not know.

**Comment by MarcusSpecht** [comment]
Alright I see. So thanks for all the effort. I will continue to narrow the problem and get back to you if I"ll find a solution.

**Comment by maximcus** [comment]
ok, thaks to you to

**Comment by maximcus** [comment]
I have come up with a wild proposition for you, @MarcusSpecht. Since you are the only one i know who is experiencing this issues it will be very convenient for me to try and run my tests on your machine. We can do it via TeamViewer or something like it. 

To be clear i do not think it is a good idea to give access to your machine to some stranger on internet, but hey, maybe you love to live dangerously)

So if you up to this, then we can try that, but i will have time only two weeks from now.

**Comment by MarcusSpecht** [comment]
Sounds good to me. I'll be pretty busy today. I live in Berlin so I should be 1 hour early if you are in Moscow. Today afer 6pm or tomorrow or monday would fine for me.

**Comment by maximcus** [comment]
I will have time only after September 12, so not on this week

**Comment by buffcode** [comment]
I have the same issue on a tablet (Dell) running Windows 10 Pro with Anniversary Update. I can confirm that the keyboard fails to show since the update.
The window slides up a bit (differs in size and does not match the OSK height), without a keyboard appearing. The TabTip and TabTip32 processes are running. Clicking the tray icon opens up the keyboard every time.

Adding `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\TabletTip\1.7\EnableDesktopModeAutoInvoke=1` to the registry did not change the behaviour.

WPFTabTip is run with `IgnoreAll` (so without detection magic) but the tablet reports a physical keyboard.
Turning on/off the Windows Tablet mode does not change the behaviour.

In the mean time there was an [update](http://stackoverflow.com/a/39385492/740183) to the StackOverflow post with as probable solution via PostMessage.

**Comment by maximcus** [comment]
@buffcode, try to resolve this issue if you can, i do not have a device to test and reproduce this problem. Frankly i added Windows 10 support as an afterthought, because my clients do not use it yet.

**Comment by beast83** [comment]
I have the same problem and I'm not familiar with the process of Microsoft's auto updates. Is it a candidate for KB release or I have to install it only via package manager? Can I see the KB number where this problem is fixed somewhere on GitHub? Thank you.

**Comment by maximcus** [comment]
@beast83 this issue is still not resolved. Anyone who can address this issue is welcome to do it.

**Comment by beast83** [comment]
It's solved by buffcode somehow, isn't it? See Patch for Windows 10 Anniversary Update #3 .

**Comment by maximcus** [comment]
@beast83, not it is not. He gave it a try, but his solution was only partial, and was not accepted. You can read the discussion of this particular pull request for more details.

**Comment by beast83** [comment]
I found probably my problem. I called TabTip.exe on GotTouchCapture explicitly. But it was done just because of problems with non-displayed keyboard. But now when we are getting to release the newer version of the application the problem appeared. We have two same tablets one before and one after anniversary update and the result is the same. I throw the TabTip calling away and problem is fixed on my newer one. My collegue will check the older one. It leads to the conclusion that the problem is somewhere in hidden/required update released independently on AU. Maybe can help to someone (targeting 4.6).

**Comment by beast83** [comment]
Sorry wrong thread.

**Comment by Wardog33** [comment]
Either of you guys come up with a solution for the Windows 10 issue? I would really like to be able to use this, but I'm experiencing the same "disturbance of the keyboard". I'm running on a tablet with no keyboard attached. Many times I will click on an input (textbox) and it will pop and then disappear and cant get the keyboard to show at all. The only thing that works is selecting the keyboard icon in the taskbar.

**Comment by Wardog33** [comment]
For anyone that is experiencing issues with Windows 10 and a "disturbance of the keyboard" / intermittent show/hiding, allow me to share what has worked for me. I'm no longer using the WPFTabTip class and no longer binding the TabTipAutomation to the controls that I want the onboard keyboard to respond to. 

It is my belief that Microsoft fixed what we programmers have been trying to do as a work around and now MS supports it natively since their last update. On your tablet just go to Settings -> Devices -> Typing and select Show touch keyboard when not in tablet mode and there's no keyboard attached. 

Note: Still need to use the InputScope to toggle between alphanumeric and number keyboards for individual inputs (textboxes, passwordboxes, etc.) but it works like a dream now and it is exactly back to how it worked before the update. Hopefully this helps someone out there who has tirelessly looked for answers.

**Comment by serlug** [comment]
I was helped to remove the keyboard from the Device Manager, after which it was suggested to restart Windows. After the launch, this problem has disappeared and the process TabTip also no longer exists in the Task Manager. I hope I could help someone.
P.S.: Sorry for translate.google.ru but my English is bad.

Мне помогло удаление клавиатуры из Диспетчера устройств, после чего было предложено перезагрузить Windows. После запуска такая проблема исчезла и процесса TabTip тоже больше нет в Диспетчере задач. Надеюсь смог кому-то помочь.
